snapshots:
  start: "2013-01-01"
  end: "2014-01-01"

enable:
  retrieve: auto             # Lascia auto (gestisce il download intelligente)
  retrieve_databundle: false # METTI FALSE. Hai già i dati grezzi (mappe, ecc.) dalle run precedenti.
  retrieve_cost_data: false  # IMPORTANTE: METTI FALSE. Se metti true, sovrascriverà il tuo file csv con i costi del nucleare!
  build_cutout: false        # METTI FALSE. Non vuoi ricalcolare il meteo da zero (richiede ore).
  retrieve_cutout: false     # METTI FALSE. Se hai già fatto simulazioni, hai già i file meteo (cutouts) nella cartella.
  drop_leap_day: true        # Ininfluente per la costruzione rete, lascia com'è.

sector:
  transport: false
  heating: true
  biomass: false
  industry: false
  shipping: false
  aviation: false
  agriculture: false
  fossil_fuels: true
  hydrogen_underground_storage_locations:
  - onshore    # more than 50 km from sea
  #- nearshore      # within 50 km of sea
    # - offshore  

solving:
  options:
    load_shedding: true

  solver:
    name: gurobi
    options: gurobi-custom

  solver_options:
    gurobi-custom:
      threads: 4
      method: 2
      crossover: 0
      BarConvTol: 1.0e-4
      FeasibilityTol: 1.0e-4
      MIPGap: 0.05
      BarHomogeneous: 1
      NumericFocus: 3
      ObjScale: 0.5

  modularity:
    enable: true
    nom_mod:
      nuclear_lr: 1600
      nuclear_smr: 300
      nuclear: 1000

electricity:
  extendable_carriers:
      Generator: [nuclear_lr, nuclear_smr, solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]

clustering:
  #mode: administrative
  
  #administrative:
    #level: 0    # Tutto il resto d'Europa è NUTS0 (1 nodo per nazione)
    #IT: 0       # Solo l'Italia è NUTS2 (Regioni)
    #FR: 1
  temporal:
    resolution_elec: false    # <--- Cambia 'false' in 6 (significa 1 step = 6 ore)
    resolution_sector: 12  # <--- Cambia 'false' in 6 (tiene allineati i settori)  

scenario:
  clusters:
    - 5
countries:
- FR

plotting:
  balance_map:
    bus_carriers: []
    techs: []
  tech_colors:
    nuclear_lr: "#ff8c00"   # Arancione
    nuclear_smr: "#C06C84"  # Rosa/Rosso
